apiVersion: v1
kind: Service
metadata:
  name: face-tracking
  namespace: security-tools
  labels:
    app.kubernetes.io/name: face-tracking
spec:
  selector:
    app.kubernetes.io/name: face-tracking
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
